"""initial schema

Revision ID: 80ae3d61a072
Revises: 
Create Date: 2026-09-30 11:38:44.056863+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '80ae3d61a072'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degraded_roads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('severity_percent', sa.Integer(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('passenger', 'drivers', 'copilote', 'admin', name='user_role'), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('wallet_balance_xaf', sa.Integer(), nullable=False),
    sa.Column('home_address', sa.String(length=255), nullable=True),
    sa.Column('home_lat', sa.Float(), nullable=True),
    sa.Column('home_lng', sa.Float(), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('suspended_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('opening_hours', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_district'), 'zones', ['district'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('flexible', 'taxi', name='carlinq_mode'), nullable=False),
    sa.Column('service_class', sa.Enum('eco', 'serenity', 'prestige', name='service_class'), nullable=True),
    sa.Column('validation_status', sa.Enum('pending', 'approved', 'rejected', 'suspended', 'excluded', name='driver_validation'), nullable=False),
    sa.Column('vehicle_brand', sa.String(length=80), nullable=False),
    sa.Column('vehicle_model', sa.String(length=80), nullable=False),
    sa.Column('vehicle_color', sa.String(length=40), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=False),
    sa.Column('company_type', sa.String(length=80), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('completed_rides', sa.Integer(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refusal_day', sa.Date(), nullable=True),
    sa.Column('refusal_seconds_used', sa.Integer(), nullable=False),
    sa.Column('premium_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('vehicle_plate')
    )
    op.create_index(op.f('ix_drivers_validation_status'), 'drivers', ['validation_status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('push_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('audience', sa.JSON(), nullable=False),
    sa.Column('recipients', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='document_status'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_documents_driver_id'), 'driver_documents', ['driver_id'], unique=False)
    op.create_table('driver_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=160), nullable=False),
    sa.Column('waypoints', sa.JSON(), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=False),
    sa.Column('avoid_traffic', sa.Boolean(), nullable=False),
    sa.Column('avoid_degraded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'day', 'slot', name='uq_driver_route_slot')
    )
    op.create_index(op.f('ix_driver_routes_driver_id'), 'driver_routes', ['driver_id'], unique=False)
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('flexible', 'taxi', name='carlinq_mode'), nullable=False),
    sa.Column('service_class', sa.Enum('eco', 'serenity', 'prestige', name='service_class'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'in_progress', 'completed', 'cancelled', name='ride_status'), nullable=False),
    sa.Column('places', sa.Integer(), nullable=False),
    sa.Column('taxi_zone_id', sa.Integer(), nullable=True),
    sa.Column('pickup_label', sa.String(length=200), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lng', sa.Float(), nullable=False),
    sa.Column('destination_label', sa.String(length=200), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=False),
    sa.Column('destination_lng', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('base_xaf', sa.Integer(), nullable=False),
    sa.Column('places_supplement_xaf', sa.Integer(), nullable=False),
    sa.Column('stop_supplement_xaf', sa.Integer(), nullable=False),
    sa.Column('degraded_percent', sa.Integer(), nullable=False),
    sa.Column('degraded_supplement_xaf', sa.Integer(), nullable=False),
    sa.Column('traffic_supplement_xaf', sa.Integer(), nullable=False),
    sa.Column('pause_supplement_xaf', sa.Integer(), nullable=False),
    sa.Column('total_xaf', sa.Integer(), nullable=False),
    sa.Column('commission_xaf', sa.Integer(), nullable=False),
    sa.Column('driver_earning_xaf', sa.Integer(), nullable=False),
    sa.Column('cancellation_fee_xaf', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('wallet', 'orange_money', 'mtn_momo', 'cash', name='payment_method'), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.String(length=20), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('places BETWEEN 1 AND 4', name='ck_ride_places'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['taxi_zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    op.create_index(op.f('ix_rides_passenger_id'), 'rides', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_rides_status'), 'rides', ['status'], unique=False)
    op.create_table('road_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('suggested_percent', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='report_status'), nullable=False),
    sa.Column('degraded_road_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['degraded_road_id'], ['degraded_roads.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_reports_driver_id'), 'road_reports', ['driver_id'], unique=False)
    op.create_table('weekly_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('target_rides', sa.Integer(), nullable=False),
    sa.Column('bonus_xaf', sa.Integer(), nullable=False),
    sa.Column('own_rides', sa.Integer(), nullable=False),
    sa.Column('shared_rides', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'achieved', 'failed', 'settled', name='goal_status'), nullable=False),
    sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pause_used', sa.Boolean(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bonus_xaf >= 0', name='ck_goal_bonus_positive'),
    sa.CheckConstraint('target_rides > 0', name='ck_goal_target_positive'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'week_start', name='uq_goal_driver_week')
    )
    op.create_index(op.f('ix_weekly_goals_driver_id'), 'weekly_goals', ['driver_id'], unique=False)
    op.create_index(op.f('ix_weekly_goals_status'), 'weekly_goals', ['status'], unique=False)
    op.create_index(op.f('ix_weekly_goals_week_start'), 'weekly_goals', ['week_start'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('opened_by', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('open', 'under_review', 'accepted', 'rejected', name='dispute_status'), nullable=False),
    sa.Column('refund_xaf', sa.Integer(), nullable=False),
    sa.Column('points_penalty', sa.Integer(), nullable=False),
    sa.Column('resolution_note', sa.String(length=1000), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_ride_id'), 'disputes', ['ride_id'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_table('goal_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('bonus_xaf', sa.Integer(), nullable=False),
    sa.Column('shared_total_xaf', sa.Integer(), nullable=False),
    sa.Column('owner_net_xaf', sa.Integer(), nullable=False),
    sa.Column('settled_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['weekly_goals.id'], ),
    sa.ForeignKeyConstraint(['settled_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id')
    )
    op.create_table('goal_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('helper_driver_id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'cancelled', name='goal_share_status'), nullable=False),
    sa.Column('contributed_rides', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('percent BETWEEN 1 AND 99', name='ck_share_percent_range'),
    sa.ForeignKeyConstraint(['goal_id'], ['weekly_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['helper_driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'helper_driver_id', name='uq_share_goal_helper')
    )
    op.create_index(op.f('ix_goal_shares_goal_id'), 'goal_shares', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_shares_helper_driver_id'), 'goal_shares', ['helper_driver_id'], unique=False)
    op.create_index(op.f('ix_goal_shares_status'), 'goal_shares', ['status'], unique=False)
    op.create_table('point_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_events_driver_id'), 'point_events', ['driver_id'], unique=False)
    op.create_table('ride_gps_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_gps_points_ride_id'), 'ride_gps_points', ['ride_id'], unique=False)
    op.create_table('ride_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_messages_ride_id'), 'ride_messages', ['ride_id'], unique=False)
    op.create_table('ride_pauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('supplement_xaf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_pauses_ride_id'), 'ride_pauses', ['ride_id'], unique=False)
    op.create_table('ride_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('ratee_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stars BETWEEN 1 AND 5', name='ck_rating_stars'),
    sa.ForeignKeyConstraint(['ratee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id', 'rater_id', name='uq_rating_ride_rater')
    )
    op.create_index(op.f('ix_ride_ratings_ride_id'), 'ride_ratings', ['ride_id'], unique=False)
    op.create_table('ride_refusals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('penalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id', 'driver_id', name='uq_refusal_ride_driver')
    )
    op.create_index(op.f('ix_ride_refusals_driver_id'), 'ride_refusals', ['driver_id'], unique=False)
    op.create_index(op.f('ix_ride_refusals_ride_id'), 'ride_refusals', ['ride_id'], unique=False)
    op.create_table('ride_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_status_logs_ride_id'), 'ride_status_logs', ['ride_id'], unique=False)
    op.create_table('ride_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('supplement_xaf', sa.Integer(), nullable=False),
    sa.Column('passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_stops_ride_id'), 'ride_stops', ['ride_id'], unique=False)
    op.create_table('traffic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('supplement_xaf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_events_ride_id'), 'traffic_events', ['ride_id'], unique=False)
    op.create_table('goal_ride_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['weekly_goals.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['share_id'], ['goal_shares.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id')
    )
    op.create_index(op.f('ix_goal_ride_credits_driver_id'), 'goal_ride_credits', ['driver_id'], unique=False)
    op.create_index(op.f('ix_goal_ride_credits_goal_id'), 'goal_ride_credits', ['goal_id'], unique=False)
    op.create_table('wallet_txs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_xaf', sa.Integer(), nullable=False),
    sa.Column('balance_after_xaf', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('goal_settlement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_settlement_id'], ['goal_settlements.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_txs_kind'), 'wallet_txs', ['kind'], unique=False)
    op.create_index(op.f('ix_wallet_txs_user_id'), 'wallet_txs', ['user_id'], unique=False)
    op.create_table('goal_settlement_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('amount_xaf', sa.Integer(), nullable=False),
    sa.Column('wallet_tx_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['goal_settlements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_tx_id'], ['wallet_txs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_settlement_lines_driver_id'), 'goal_settlement_lines', ['driver_id'], unique=False)
    op.create_index(op.f('ix_goal_settlement_lines_settlement_id'), 'goal_settlement_lines', ['settlement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_settlement_lines_settlement_id'), table_name='goal_settlement_lines')
    op.drop_index(op.f('ix_goal_settlement_lines_driver_id'), table_name='goal_settlement_lines')
    op.drop_table('goal_settlement_lines')
    op.drop_index(op.f('ix_wallet_txs_user_id'), table_name='wallet_txs')
    op.drop_index(op.f('ix_wallet_txs_kind'), table_name='wallet_txs')
    op.drop_table('wallet_txs')
    op.drop_index(op.f('ix_goal_ride_credits_goal_id'), table_name='goal_ride_credits')
    op.drop_index(op.f('ix_goal_ride_credits_driver_id'), table_name='goal_ride_credits')
    op.drop_table('goal_ride_credits')
    op.drop_index(op.f('ix_traffic_events_ride_id'), table_name='traffic_events')
    op.drop_table('traffic_events')
    op.drop_index(op.f('ix_ride_stops_ride_id'), table_name='ride_stops')
    op.drop_table('ride_stops')
    op.drop_index(op.f('ix_ride_status_logs_ride_id'), table_name='ride_status_logs')
    op.drop_table('ride_status_logs')
    op.drop_index(op.f('ix_ride_refusals_ride_id'), table_name='ride_refusals')
    op.drop_index(op.f('ix_ride_refusals_driver_id'), table_name='ride_refusals')
    op.drop_table('ride_refusals')
    op.drop_index(op.f('ix_ride_ratings_ride_id'), table_name='ride_ratings')
    op.drop_table('ride_ratings')
    op.drop_index(op.f('ix_ride_pauses_ride_id'), table_name='ride_pauses')
    op.drop_table('ride_pauses')
    op.drop_index(op.f('ix_ride_messages_ride_id'), table_name='ride_messages')
    op.drop_table('ride_messages')
    op.drop_index(op.f('ix_ride_gps_points_ride_id'), table_name='ride_gps_points')
    op.drop_table('ride_gps_points')
    op.drop_index(op.f('ix_point_events_driver_id'), table_name='point_events')
    op.drop_table('point_events')
    op.drop_index(op.f('ix_goal_shares_status'), table_name='goal_shares')
    op.drop_index(op.f('ix_goal_shares_helper_driver_id'), table_name='goal_shares')
    op.drop_index(op.f('ix_goal_shares_goal_id'), table_name='goal_shares')
    op.drop_table('goal_shares')
    op.drop_table('goal_settlements')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_ride_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_weekly_goals_week_start'), table_name='weekly_goals')
    op.drop_index(op.f('ix_weekly_goals_status'), table_name='weekly_goals')
    op.drop_index(op.f('ix_weekly_goals_driver_id'), table_name='weekly_goals')
    op.drop_table('weekly_goals')
    op.drop_index(op.f('ix_road_reports_driver_id'), table_name='road_reports')
    op.drop_table('road_reports')
    op.drop_index(op.f('ix_rides_status'), table_name='rides')
    op.drop_index(op.f('ix_rides_passenger_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_driver_routes_driver_id'), table_name='driver_routes')
    op.drop_table('driver_routes')
    op.drop_index(op.f('ix_driver_documents_driver_id'), table_name='driver_documents')
    op.drop_table('driver_documents')
    op.drop_table('push_campaigns')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_drivers_validation_status'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_zones_district'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('degraded_roads')
    # ### end Alembic commands ###
    for enum_name in ('user_role', 'carlinq_mode', 'service_class', 'driver_validation', 'document_status',
                      'ride_status', 'payment_method', 'report_status', 'goal_status', 'dispute_status',
                      'goal_share_status'):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
