name: carlinq
description: "Carlinq - Application mobile de transport collaboratif bi-mode (Carlinq Flexible + Carlinq Taxi)."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0D47A1"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: false
